add-highlighter global number_lines -relative

# Leader key mappings (leader = ',' by default)
# equivalent of F and T in VIM
map global user f <a-f> -docstring 'jump to previous'
map global user t <a-t> -docstring 'jump until previous'
map global user F <a-F> -docstring 'jump to previous; extend selection'
map global user T <a-T> -docstring 'jump until previous; extend selection'

# use tabs
set-option global indentwidth 0

set-option global termcmd 'urxvt -e sh -c'
set global ui_options ncurses_assistant=dilbert

alias global colo colorscheme
#colorscheme base16
#colorscheme base16_grayscale
#colorscheme base16_atelierForest
#colorscheme base16_colors
# colorscheme base16_solarized
colorscheme base16_tomorrow
# colorscheme base16_tube
#colorscheme dracula
#colorscheme gotham
#colorscheme wal
